# .github/workflows/build-docker-image.yml
name: Build Docker Image

on:
  workflow_call:
    inputs:
      directory:
        description: 'Directory containing the Dockerfile'
        required: true
        type: string
      dockerfile-path:
        description: 'Path to the Dockerfile'
        required: true
        type: string
      image-tag:
        description: 'Tag for the Docker image'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: List files in context directory
      run: ls -R ${{ inputs.directory }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      id: build
      uses: docker/build-push-action@v3
      with:
        file: ${{ inputs.dockerfile-path }}
        load: true
        push: false
        tags: ${{ inputs.image-tag }}
