name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in context directory
      run: ls -R ./Permission-Microservice

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        file: ./Permission-Microservice/Dockerfile
        load: true
        push: false
        tags: jahanzaibbhurgri/permission:latest