name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in context directory
      run: ls 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      working-directory: Permission-Microservice
      uses: docker/build-push-action@v3
      with:
        context: ./Permission-Microservice
        push: false
        load: true  
        tags: jahanzaibbhurgri/permission:latest
