name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
     
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'  # Replace with the version you use locally


    - name: List files in context directory
      run: ls -R ./Permission-Microservice

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      id: build
      uses: docker/build-push-action@v3
      with:
        file: ./Permission-Microservice/Dockerfile
        load: true
        push: false
        tags: jahanzaibbhurgri/permission:latest

    - name: Extract npm logs
      run: |
        docker run --rm jahanzaibbhurgri/permission:latest cat /npm-install.log > npm-install.log
      